# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#about"
    weight: 10
  - name: Topics of our meeting
    url: "#topics"
    weight: 20
  - name: Future Schedule
    url: "#schedule"
    weight: 30
  - name: Research Papers
    url: "#papers"
    weight: 50
  - name: Affiliates
    url: "#affiliates"
    weight: 50
  - name: Contact
    url: "#contact"
    weight: 60
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
